In [ ]:
#Instalando bibliotecas necessárias

!pip install numpy
!pip install pandas
!pip install sklearn
!pip install matplotlib

In [2]:
import numpy as np
import pandas
import sklearn
import matplotlib

In [3]:
lista = [1, 2, 3, 4, 5, 6]
array = np.array(lista)

In [4]:
print(type(lista))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
arr_zeros = np.zeros(10)
print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
array[0] = 9
print(array)

[9 2 3 4 5 6]


In [7]:
matriz_zeros = np.zeros((5, 3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
lista_de_notas = [9.8, 5.6, 7.8, 9.1, 6.5]

notas = np.array(lista_de_notas)
print('Maximo', notas.max())
print('Minimo', notas.min())
print('Desvio padrão', notas.std())
print('Media', notas.mean())
print('Posição menor', notas.argmin())

Maximo 9.8
Minimo 5.6
Desvio padrão 1.5628179676469045
Media 7.76
Posição menor 1
